### PR TITLE
Add item scale factor parameter

### PR DESCRIPTION
**Pull request by Oubi256**
I didn't like that I can't change the default icon scale after clicking. Now it can be specified. 1 - the scale is twice the standard size (default behavior), 0.5 -scale half of the standard, etc.

### CODE REVIEW

**Comment by vizhan-lanars** [comment]
Hi.
Thanks for your contribution.
We are not consider making that property customisable.
But you can fork for your needs.

**Comment by canaan5** [comment]
This is wrong. 

by default it should be customisable. I really don't like the scale on tap.

**Comment by vizhan-lanars** [comment]
Hi, @canaan5 @Oubi256 
Please check version 1.3.0 with a new `scaleFactor` parameter.

**Comment by canaan5** [comment]
Thank you so much @vizhan-lanars, this is perfect.

**Pull request closed without merging**
